name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        touch results.log
        for test in test/*.py; do
          echo Logs for $test: |& tee -a results.log
          python3 $test |& tee -a results.log
        done

    - name: Test
      run: python -m unittest discover test

    - name: Save logs
      uses: actions/upload-artifact@v2
      with:
        name: results.log
        path: results.log
